name: CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  pipeline:
    uses: L-and-D/LnD/.github/workflows/backend.yml@main

    with:
      service: "user-service"
      image: ghcr.io/l-and-d/ld-user-service
      trigger: ${{ github.event_name }}

    secrets: inherit